engines:
  govet:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM

ratings:
  paths:
    - "**.go"
