version: "2"         # required to adjust maintainability checks
checks:
  method-complexity:
    config:
      threshold: 15
plugins:
  govet:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO

ratings:
  paths:
    - "**.go"
