version: 2
jobs:
  prepare:
    docker:
      - image: therecipe/qt:linux
    steps:
      - run:
          name: Get checkout script
          command: apt-get update -qq && apt-get install -y -qq wget curl && mkdir -p .circleci && wget https://raw.githubusercontent.com/Nordgedanken/Morpheus/develop/.circleci/checkout.sh -O .circleci/checkout.sh && chmod +x .circleci/checkout.sh
      - run:
          name: Checkout Morpheus
          command: bash .circleci/checkout.sh
      - run:
          name: Set PATH to correct value
          command: echo 'export PATH=/usr/local/go/bin:/usr/local/go_workspace/bin:~/.go_workspace/bin:/home/user/work/bin:$GOBIN:$PATH' >> $BASH_ENV
      - run:
          name: Get Glide
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: curl https://glide.sh/get | sh
      - run:
          name: Get Go Dependencies
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: glide install
      - run:
          name: Get Ginko CLI
          command: go get -u -v github.com/onsi/ginkgo/ginkgo && go get -u -v github.com/onsi/gomega
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /home/user/work/
          # Must be relative path from root
          paths:
            - src/
            - bin/ginkgo
  build_linux:
    docker:
      - image: therecipe/qt:linux
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/user/work/
      - run:
          name: Run Build
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: $GOPATH/bin/qtdeploy build linux
      - run:
          name: Prepare Deb Generating
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: apt-get update -qq && apt-get install -y -qq wget && wget -q -O - --no-check-certificate https://raw.githubusercontent.com/mh-cbon/latest/master/install.sh | GH=mh-cbon/go-bin-deb sh -xe && apt-get update -qq && apt-get install build-essential lintian -y -qq
      - run:
          name: Deb Generating
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: mkdir debian && go-bin-deb generate -o debian
      - store_artifacts:
          path: /home/user/work/src/github.com/Nordgedanken/Morpheus/debian/
          destination: debian
  test:
    docker:
      - image: therecipe/qt:linux
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/user/work/
      - run:
          name: Generate additional binding files
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: $GOPATH/bin/qtrcc desktop && $GOPATH/bin/qtmoc desktop
      - run:
          name: Build Tests
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: $GOPATH/bin/ginkgo build /home/user/work/src/github.com/Nordgedanken/Morpheus/
          no_output_timeout: 1200
      - run:
          name: Run Tests
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: $GOPATH/bin/ginkgo -r -p --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress /home/user/work/src/github.com/Nordgedanken/Morpheus/Morpheus.test
          no_output_timeout: 1200
      - run:
          name: Debug Print directory
          shell: /bin/sh
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: ls -lah
      - store_test_results:
              path: /home/user/work/src/github.com/Nordgedanken/Morpheus/junit.xml
  lint:
    docker:
      - image: therecipe/qt:linux
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/user/work/
      - run:
          name: Run Lint
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: chmod +x scripts/lint.sh && scripts/lint.sh
          no_output_timeout: 1200
      - store_test_results:
              path: /home/user/work/src/github.com/Nordgedanken/Morpheus/junit.xml
  build_win_static:
    docker:
      - image: therecipe/qt:windows_64_static
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/user/work/
      - run:
          name: Run Build
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: $GOPATH/bin/qtdeploy build windows
      - store_artifacts:
          path: /home/user/work/src/github.com/Nordgedanken/Morpheus/deploy/windows/Morpheus.exe
          destination: Morpheus.exe
workflows:
  version: 2
  build-test:
    jobs:
      - prepare
      - build_linux:
          requires:
            - prepare
      - build_win_static:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - lint:
          requires:
            - prepare
notify:
  webhooks:
    - url: https://riot.nordgedanken.de:4051/services/hooks/Y2lyY2xlY2lfc2VydmljZQ
