version: 2
jobs:
  prepare:
    docker:
      - image: therecipe/qt:linux
    steps:
      - run:
          name: Get Morpheus
          command: go get -u -v -d github.com/Nordgedanken/Morpheus/...
      - run:
          name: Get Ginko CLI
          command: go get -u -v github.com/onsi/ginkgo/ginkgo && go get -u -v github.com/onsi/gomega
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /home/user/work/
          # Must be relative path from root
          paths:
            - src/
            - bin/ginkgo
  build_linux:
    docker:
      - image: therecipe/qt:linux
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/user/work/
      - run:
          name: Run Build
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: $GOPATH/bin/qtdeploy build linux
  test:
    docker:
      - image: therecipe/qt:linux
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/user/work/
      - run:
          name: Generate additional binding files
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: $GOPATH/bin/qtrcc desktop && $GOPATH/bin/qtmoc desktop
      - run:
          name: Build Tests
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: $GOPATH/bin/ginkgo build /home/user/work/src/github.com/Nordgedanken/Morpheus/
          no_output_timeout: 1200
      - run:
          name: Run Tests
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: $GOPATH/bin/ginkgo -r -p --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress /home/user/work/src/github.com/Nordgedanken/Morpheus/package.test
          no_output_timeout: 1200
      - store_test_results:
              path: /home/user/work/src/github.com/Nordgedanken/Morpheus/
  build_win_static:
    docker:
      - image: therecipe/qt:windows_64_static
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /home/user/work/
      - run:
          name: Run Build
          working_directory: /home/user/work/src/github.com/Nordgedanken/Morpheus/
          command: $GOPATH/bin/qtdeploy build windows
workflows:
  version: 2
  build-test:
    jobs:
      - prepare
      - build_linux:
          requires:
            - prepare
      - build_win_static:
          requires:
            - prepare
      - test:
          requires:
            - prepare