version: 2
jobs:
  build:
    docker:
      - image: therecipe/qt:linux
        environment:
          DESKTOP: true
    steps:
      - run:
          name: Get Morpheus
          command: go get -u -v -d github.com/Nordgedanken/Morpheus/...
      - run:
          name: qt-binding
          command: go get -u -v github.com/therecipe/qt/cmd/...
      #- run:
      #    name: qt
      #    command: if [[ "$OS" == "linux" ]]; then chmod +x ./.ci/linux.sh && ./.ci/linux.sh; fi
      - run:
          name: qt-binding setup
          command: $GOPATH/bin/qtsetup full desktop
      - run: if [[ "$DESKTOP" == "true" ]]; then cd $GOPATH/src/github.com/Nordgedanken/Morpheus/ && $GOPATH/bin/qtdeploy test desktop; fi