# After registering a name on build.snapcraft.io, commit an uncommented line:
name: morpheus
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Matrix client written in Go-QT
description: |
  A Matrix client written in Go-QT.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  morpheus:
    command: morpheus

parts:
  morpheus:
    source: https://github.com/Nordgedanken/Morpheus.git
    plugin: nil
    build-packages:
      - golang-go
      - qt5-qmake
      - qtbase5-dev
      - build-essential
      - libgl1-mesa-dev
      - libpulse-dev
    after: [desktop-qt5]
    build: |
      export GOPATH="$HOME/go/"
      mkdir $GOPATH
      go get -u -v github.com/therecipe/qt/cmd/...
      QT_PKG_CONFIG=true $GOPATH/bin/qtsetup
      $GOPATH/bin/qtdeploy build linux
    install: |
      mv .circleci/Morpheus.sh $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus.sh
      sed -i -e 's/$appname/Morpheus_bin/g' $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus.sh
      ln -s $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus.sh $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus
      ln -s $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus.sh $SNAPCRAFT_PART_INSTALL/usr/bin/morpheus
      mv deploy/linux/Morpheus $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus_bin
      mv deploy/linux/lib/* $SNAPCRAFT_PART_INSTALL/usr/local/lib/
      mv deploy/linux/plugins/* $SNAPCRAFT_PART_INSTALL/usr/local/Morpheus/plugins/
      mv deploy/linux/qml/* $SNAPCRAFT_PART_INSTALL/usr/local/Morpheus/qml/
