# After registering a name on build.snapcraft.io, commit an uncommented line:
name: morpheus
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Matrix client written in Go-QT
description: |
  A Matrix client written in Go-QT.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  morpheus:
    command: morpheus

parts:
  morpheus:
    source: https://github.com/Nordgedanken/Morpheus.git
    plugin: nil
    build-packages:
      - build-essential
      - libgl1-mesa-dev
      - libpulse-dev
      - curl
      - libfontconfig
      - xvfb
      - software-properties-common
    build: |
      add-apt-repository -y ppa:gophers/archive
      apt-get -qq update
      apt-get -y -qq install golang-1.9-go
      export PATH="$PATH:/usr/lib/go-1.9/bin/"
      export GOPATH="$HOME/go/"
      mkdir $GOPATH
      go get -u -d -v github.com/therecipe/qt/cmd/...
      export DISPLAY=:0
      curl -L --retry 10 --retry-delay 10 -o /tmp/qt-unified-linux-x64-online.run https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
      chmod +x /tmp/qt-unified-linux-x64-online.run
      xvfb-run /tmp/qt-unified-linux-x64-online.run --script $GOPATH/src/github.com/therecipe/qt/internal/ci/iscript.qs LINUX=true
      rm -f /tmp/qt-unified-linux-x64-online.run
      export PKG_CONFIG_PATH=/opt/qt58/lib/pkgconfig
      export QT_DOC_DIR=/opt/qt58/doc
      export QT_MISC_DIR=/opt/qt58
      export QT_DIR=/opt/Qt
      go install github.com/therecipe/qt/cmd/...
      export CGO_CXXFLAGS_ALLOW=".*"
      export CGO_LDFLAGS_ALLOW=".*"
      export CGO_CFLAGS_ALLOW=".*"
      $GOPATH/bin/qtsetup check
      $GOPATH/bin/qtsetup prep
      $GOPATH/bin/qtsetup generate
      $GOPATH/bin/qtsetup install
      mkdir -p $GOPATH/src/github.com/Nordgedanken/Morpheus/
      mv ./* $GOPATH/src/github.com/Nordgedanken/Morpheus/
      cd $GOPATH/src/github.com/Nordgedanken/Morpheus/
      curl -L https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep && chmod +x $GOPATH/bin/dep
      dep ensure
      $GOPATH/bin/qtdeploy build linux
    install: |
      mv .circleci/Morpheus.sh $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus.sh
      sed -i -e 's/$appname/Morpheus_bin/g' $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus.sh
      ln -s $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus.sh $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus
      ln -s $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus.sh $SNAPCRAFT_PART_INSTALL/usr/bin/morpheus
      mv deploy/linux/Morpheus $SNAPCRAFT_PART_INSTALL/usr/bin/Morpheus_bin
      mv deploy/linux/lib/* $SNAPCRAFT_PART_INSTALL/usr/local/lib/
      mv deploy/linux/plugins/* $SNAPCRAFT_PART_INSTALL/usr/local/Morpheus/plugins/
      mv deploy/linux/qml/* $SNAPCRAFT_PART_INSTALL/usr/local/Morpheus/qml/
